---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Add Docker users to the Docker group (Ubuntu)
  become: yes
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
  when: ansible_os_family == 'Debian'

